baseURL: "https://the-creative-blog.netlify.app/"
title: "The Creative"
theme: "ananke"  # ⚠️ Change this if you're using a different theme folder name
languageCode: "en-us"
defaultContentLanguage: "en"
enableRobotsTXT: true
paginate: 10
summaryLength: 70
googleAnalytics: ""

menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Discover
      url: "/discover/"
      weight: 2
    - name: Tips
      url: "/tips/"
      weight: 3
    - name: Categories
      url: "/categories/"
      weight: 4
    - name: About
      url: "/about/"
      weight: 5

params:
  description: "Free content to inspire you – Discover News, Science, Motivation and more."
  author: "Admin"
  showReadMore: true
  showRelatedPosts: true
  mainSections: ["posts"]
  favicon: "images/favicon.png"
  custom_css: ["css/custom.css"]
  dateFormat: "Jan 2, 2006"

taxonomies:
  category: "categories"
  tag: "tags"
  author: "authors"
  location: "locations"
