# ==========================
# Netlify Build Configuration
# ==========================

[build]
  # Folder where Hugo will output your final site
  publish = "public"

  # Command Netlify runs to build your Hugo site
  command = "hugo --verbose"

# ==========================
# Environment variables for production
# ==========================
[context.production.environment]
  HUGO_VERSION = "0.125.4"      # or the latest stable version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# ==========================
# Deploy preview environment (for PRs, previews)
# ==========================
[context.deploy-preview.environment]
  HUGO_VERSION = "0.125.4"
  HUGO_ENV = "development"

# ==========================
# Branch deploy environment (e.g. feature branches)
# ==========================
[context.branch-deploy.environment]
  HUGO_VERSION = "0.125.4"

# ==========================
# Redirects (used for Netlify CMS admin panel)
# ==========================
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
